In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [224]:
df=pd.read_csv(r"cardio_train.csv",sep=";")

In [110]:
df.shape

(69301, 13)

In [111]:
df.isnull().any().sum()

0

In [112]:
df.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0  988  22469       1     155    69.0    130     80            2     2      0   
1  989  14648       1     163    71.0    110     70            1     1      0   
2  990  21901       1     165    70.0    120     80            1     1      0   
3  991  14549       2     165    85.0    120     80            1     1      1   
4  992  23393       1     155    62.0    120     80            1     1      0   

   alco  active  cardio  
0     0       1       0  
1     0       1       1  
2     0       1       0  
3     1       1       0  
4     0       1       0

In [113]:
df.cardio.value_counts()

0    34679
1    34622
Name: cardio, dtype: int64

In [114]:
df.drop('id',axis=1,inplace=True)


In [116]:
df.head()

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0  22469       1     155    69.0    130     80            2     2      0   
1  14648       1     163    71.0    110     70            1     1      0   
2  21901       1     165    70.0    120     80            1     1      0   
3  14549       2     165    85.0    120     80            1     1      1   
4  23393       1     155    62.0    120     80            1     1      0   

   alco  active  cardio  
0     0       1       0  
1     0       1       1  
2     0       1       0  
3     1       1       0  
4     0       1       0

In [117]:
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
columns_to_scale = ['age', 'height', 'weight', 'ap_hi', 'ap_lo']
df[columns_to_scale] = standardScaler.fit_transform(df[columns_to_scale])

In [118]:
df.head()

age  gender    height    weight     ap_hi     ap_lo  cholesterol  \
0  1.216018       1 -1.140999 -0.361739  0.007562 -0.088052            2   
1 -1.953915       1 -0.166017 -0.222690 -0.121658 -0.140935            1   
2  0.985802       1  0.077728 -0.292214 -0.057048 -0.088052            1   
3 -1.994041       2  0.077728  0.750657 -0.057048 -0.088052            1   
4  1.590525       1 -1.140999 -0.848413 -0.057048 -0.088052            1   

   gluc  smoke  alco  active  cardio  
0     2      0     0       1       0  
1     1      0     0       1       1  
2     1      0     0       1       0  
3     1      1     1       1       0  
4     1      0     0       1       0

In [123]:
gender=pd.get_dummies(df['gender'],prefix='Male',drop_first=True)

In [225]:
cholesterol=pd.get_dummies(df['cholesterol'],prefix='Normal',drop_first=True)


In [127]:
gluc=pd.get_dummies(df['gluc'],prefix='gluc',drop_first=True)

In [128]:
smoke=pd.get_dummies(df['smoke'],prefix='smoke',drop_first=True)

In [129]:
alco=pd.get_dummies(df['alco'],prefix='alco',drop_first=True)

In [130]:
active=pd.get_dummies(df['active'],prefix='active',drop_first=True)

In [135]:
dummy_df=pd.concat([gender,cholesterol,gluc,smoke,alco,active],axis=1)

In [138]:
df.head()

age  gender    height    weight     ap_hi     ap_lo  cholesterol  \
0  1.216018       1 -1.140999 -0.361739  0.007562 -0.088052            2   
1 -1.953915       1 -0.166017 -0.222690 -0.121658 -0.140935            1   
2  0.985802       1  0.077728 -0.292214 -0.057048 -0.088052            1   
3 -1.994041       2  0.077728  0.750657 -0.057048 -0.088052            1   
4  1.590525       1 -1.140999 -0.848413 -0.057048 -0.088052            1   

   gluc  smoke  alco  active  cardio  
0     2      0     0       1       0  
1     1      0     0       1       1  
2     1      0     0       1       0  
3     1      1     1       1       0  
4     1      0     0       1       0

In [139]:
df.drop(['gender','cholesterol','gluc','smoke','alco','active'],axis=1,inplace=True)

In [140]:
df.head()

age    height    weight     ap_hi     ap_lo  cardio
0  1.216018 -1.140999 -0.361739  0.007562 -0.088052       0
1 -1.953915 -0.166017 -0.222690 -0.121658 -0.140935       1
2  0.985802  0.077728 -0.292214 -0.057048 -0.088052       0
3 -1.994041  0.077728  0.750657 -0.057048 -0.088052       0
4  1.590525 -1.140999 -0.848413 -0.057048 -0.088052       0

In [141]:
main_df=pd.concat([df,dummy_df],axis=1)

In [142]:
main_df.head()

age    height    weight     ap_hi     ap_lo  cardio  Male_2  Normal_2  \
0  1.216018 -1.140999 -0.361739  0.007562 -0.088052       0       0         1   
1 -1.953915 -0.166017 -0.222690 -0.121658 -0.140935       1       0         0   
2  0.985802  0.077728 -0.292214 -0.057048 -0.088052       0       0         0   
3 -1.994041  0.077728  0.750657 -0.057048 -0.088052       0       1         0   
4  1.590525 -1.140999 -0.848413 -0.057048 -0.088052       0       0         0   

   Normal_3  gluc_2  gluc_3  smoke_1  alco_1  active_1  
0         0       1       0        0       0         1  
1         0       0       0        0       0         1  
2         0       0       0        0       0         1  
3         0       0       0        1       1         1  
4         0       0       0        0       0         1

In [165]:
X=main_df.iloc[:,:-1]
y=main_df['cardio']

In [172]:
y.value_counts()

0    34679
1    34622
Name: cardio, dtype: int64

In [206]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25 , random_state=0)

In [207]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((51975, 13), (17326, 13), (51975,), (17326,))

In [208]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()
logistic.fit(X_train,y_train)

C:\Users\degananda.reddy\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [216]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
accuracy=accuracy_score(y_train,logistic.predict(X_train))

In [210]:
confusion_matrix(y_test,logistic.predict(X_test))

array([[8653,    0],
       [   0, 8673]], dtype=int64)

In [217]:
accuracy


1.0

In [212]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors = 8)
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

In [213]:
knn_pred=knn_classifier.predict(X_test)

In [214]:
knn_accuracy=accuracy_score(y_test,knn_pred)

In [215]:
knn_accuracy

0.9981530647581669

In [184]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=10, criterion = 'entropy', random_state = 50)
rf_classifier.fit(X_train,y_train)
pred=rf_classifier.predict(X_test)
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(pred,y_test))
print(confusion_matrix(pred,y_test))
classification_report(pred,y_test)



1.0
[[10401     0]
 [    0 10390]]


'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00     10401\n           1       1.00      1.00      1.00     10390\n\n    accuracy                           1.00     20791\n   macro avg       1.00      1.00      1.00     20791\nweighted avg       1.00      1.00      1.00     20791\n'

In [78]:
#optimisation using RandomisedSeachCV
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
est=RandomForestClassifier(n_jobs=-1)
rf_params={'max_depth':[3,5,10,None],
              'n_estimators':[10,100,200,300,400,500],
              'max_features':randint(1,3),
               'criterion':['gini','entropy'],
               'bootstrap':[True,False],
               'min_samples_leaf':randint(1,4),
              }

def hypertuning_rscv(est, p_distr, nbr_iter,X,y):
    rdmsearch = RandomizedSearchCV(est, param_distributions=p_distr,
                                  n_jobs=-1, n_iter=nbr_iter, cv=9)
    #CV = Cross-Validation ( here using Stratified KFold CV)
    rdmsearch.fit(X,y)
    ht_params = rdmsearch.best_params_
    ht_score = rdmsearch.best_score_
    return ht_params, ht_score

rf_parameters, rf_ht_score = hypertuning_rscv(est, rf_params, 40, X, y)



C:\Users\degananda.reddy\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:715: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


In [81]:
real_classifier=RandomForestClassifier(n_estimators=500,criterion='gini',max_depth=3,bootstrap=True,max_features=2,min_samples_leaf=1)
real_classifier.fit(X_train,y_train)
real_pred=real_classifier.predict(X_test)
print(accuracy_score(real_pred,y_test))
print(confusion_matrix(real_pred,y_test))

C:\Users\degananda.reddy\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


0.7220431917656679
[[8106 3484]
 [2295 6906]]


In [218]:
classifier=xgboost.XGBClassifier()
classifier.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [219]:
xgpred=classifier.predict(X_test)

In [220]:
accuracy_score(y_test,xgpred)

1.0

In [221]:
params={
 "learning_rate"    : [0.05, 0.10, 0.15, 0.20, 0.25, 0.30 ] ,
 "max_depth"        : [ 3, 4, 5, 6, 8, 10, 12, 15],
 "min_child_weight" : [ 1, 3, 5, 7 ],
 "gamma"            : [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
 "colsample_bytree" : [ 0.3, 0.4, 0.5 , 0.7 ]
    
}

In [222]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
classifier=xgboost.XGBClassifier()
random_search=RandomizedSearchCV(classifier,param_distributions=params,n_iter=5,scoring='roc_auc',n_jobs=-1,cv=5,verbose=3)
random_search.fit(X,y)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 out of  25 | elapsed:  1.3min finished


RandomizedSearchCV(cv=5, error_score='raise-deprecating',
                   estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                           colsample_bylevel=1,
                                           colsample_bynode=1,
                                           colsample_bytree=1, gamma=0,
                                           learning_rate=0.1, max_delta_step=0,
                                           max_depth=3, min_child_weight=1,
                                           missing=None, n_estimators=100,
                                           n_jobs=1, nthread=None,
                                           objective='binary:logistic',
                                           random_state=0, reg_alpha=0...
                                           seed=None, silent=None, subsample=1,
                                           verbosity=1),
                   iid='warn', n_iter=5, n_jobs=-1,
                   param_distribu

In [89]:

random_search.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.3, gamma=0.0,
              learning_rate=0.2, max_delta_step=0, max_depth=3,
              min_child_weight=3, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [91]:
random_search.best_params_

{'min_child_weight': 3,
 'max_depth': 3,
 'learning_rate': 0.2,
 'gamma': 0.0,
 'colsample_bytree': 0.3}

In [93]:
classifier=xgboost.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.3, gamma=0.0,
              learning_rate=0.2, max_delta_step=0, max_depth=3,
              min_child_weight=3, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [94]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(classifier,X,y,cv=10)

C:\Users\degananda.reddy\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\degananda.reddy\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\degananda.reddy\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\degananda.reddy\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preproces

In [95]:
score

array([0.7306305 , 0.73120762, 0.74300144, 0.74227994, 0.73376623,
       0.73867244, 0.72972583, 0.73838384, 0.73578644, 0.73459374])