In [68]:
import pandas as pd
import matplotlib
import numpy as np
import seaborn as sns

In [69]:
matplotlib.__version__

'3.0.3'

In [2]:
df=pd.read_csv(r"cardio_train.csv",sep=";")

In [3]:
df.shape

(69301, 13)

In [4]:
df.isnull().any().sum()

0

In [5]:
df.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0  988  22469       1     155    69.0    130     80            2     2      0   
1  989  14648       1     163    71.0    110     70            1     1      0   
2  990  21901       1     165    70.0    120     80            1     1      0   
3  991  14549       2     165    85.0    120     80            1     1      1   
4  992  23393       1     155    62.0    120     80            1     1      0   

   alco  active  cardio  
0     0       1       0  
1     0       1       1  
2     0       1       0  
3     1       1       0  
4     0       1       0

In [6]:
df.cardio.value_counts()

0    34679
1    34622
Name: cardio, dtype: int64

In [7]:
df.drop('id',axis=1,inplace=True)


In [8]:
df.head()

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0  22469       1     155    69.0    130     80            2     2      0   
1  14648       1     163    71.0    110     70            1     1      0   
2  21901       1     165    70.0    120     80            1     1      0   
3  14549       2     165    85.0    120     80            1     1      1   
4  23393       1     155    62.0    120     80            1     1      0   

   alco  active  cardio  
0     0       1       0  
1     0       1       1  
2     0       1       0  
3     1       1       0  
4     0       1       0

In [9]:
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
columns_to_scale = ['age', 'height', 'weight', 'ap_hi', 'ap_lo']
df[columns_to_scale] = standardScaler.fit_transform(df[columns_to_scale])

In [10]:
df.head()

age  gender    height    weight     ap_hi     ap_lo  cholesterol  \
0  1.216018       1 -1.140999 -0.361739  0.007562 -0.088052            2   
1 -1.953915       1 -0.166017 -0.222690 -0.121658 -0.140935            1   
2  0.985802       1  0.077728 -0.292214 -0.057048 -0.088052            1   
3 -1.994041       2  0.077728  0.750657 -0.057048 -0.088052            1   
4  1.590525       1 -1.140999 -0.848413 -0.057048 -0.088052            1   

   gluc  smoke  alco  active  cardio  
0     2      0     0       1       0  
1     1      0     0       1       1  
2     1      0     0       1       0  
3     1      1     1       1       0  
4     1      0     0       1       0

In [11]:
gender=pd.get_dummies(df['gender'],prefix='Male',drop_first=True)

In [12]:
cholesterol=pd.get_dummies(df['cholesterol'],prefix='Normal',drop_first=True)


In [13]:
gluc=pd.get_dummies(df['gluc'],prefix='gluc',drop_first=True)

In [14]:
smoke=pd.get_dummies(df['smoke'],prefix='smoke',drop_first=True)

In [15]:
alco=pd.get_dummies(df['alco'],prefix='alco',drop_first=True)

In [16]:
active=pd.get_dummies(df['active'],prefix='active',drop_first=True)

In [17]:
dummy_df=pd.concat([gender,cholesterol,gluc,smoke,alco,active],axis=1)

In [18]:
df.head()

age  gender    height    weight     ap_hi     ap_lo  cholesterol  \
0  1.216018       1 -1.140999 -0.361739  0.007562 -0.088052            2   
1 -1.953915       1 -0.166017 -0.222690 -0.121658 -0.140935            1   
2  0.985802       1  0.077728 -0.292214 -0.057048 -0.088052            1   
3 -1.994041       2  0.077728  0.750657 -0.057048 -0.088052            1   
4  1.590525       1 -1.140999 -0.848413 -0.057048 -0.088052            1   

   gluc  smoke  alco  active  cardio  
0     2      0     0       1       0  
1     1      0     0       1       1  
2     1      0     0       1       0  
3     1      1     1       1       0  
4     1      0     0       1       0

In [19]:
df.drop(['gender','cholesterol','gluc','smoke','alco','active'],axis=1,inplace=True)

In [20]:
df.head()

age    height    weight     ap_hi     ap_lo  cardio
0  1.216018 -1.140999 -0.361739  0.007562 -0.088052       0
1 -1.953915 -0.166017 -0.222690 -0.121658 -0.140935       1
2  0.985802  0.077728 -0.292214 -0.057048 -0.088052       0
3 -1.994041  0.077728  0.750657 -0.057048 -0.088052       0
4  1.590525 -1.140999 -0.848413 -0.057048 -0.088052       0

In [21]:
main_df=pd.concat([df,dummy_df],axis=1)

In [22]:
main_df.head()

age    height    weight     ap_hi     ap_lo  cardio  Male_2  Normal_2  \
0  1.216018 -1.140999 -0.361739  0.007562 -0.088052       0       0         1   
1 -1.953915 -0.166017 -0.222690 -0.121658 -0.140935       1       0         0   
2  0.985802  0.077728 -0.292214 -0.057048 -0.088052       0       0         0   
3 -1.994041  0.077728  0.750657 -0.057048 -0.088052       0       1         0   
4  1.590525 -1.140999 -0.848413 -0.057048 -0.088052       0       0         0   

   Normal_3  gluc_2  gluc_3  smoke_1  alco_1  active_1  
0         0       1       0        0       0         1  
1         0       0       0        0       0         1  
2         0       0       0        0       0         1  
3         0       0       0        1       1         1  
4         0       0       0        0       0         1

In [76]:
X=main_df.iloc[:,:-1]
y=main_df['cardio']

In [84]:
X.drop('cardio',axis=1,inplace=True)

In [173]:
X.dtypes

age         float64
height      float64
weight      float64
ap_hi       float64
ap_lo       float64
Male_2        uint8
Normal_2      uint8
Normal_3      uint8
gluc_2        uint8
gluc_3        uint8
smoke_1       uint8
alco_1        uint8
dtype: object

In [24]:
y.value_counts()

0    34679
1    34622
Name: cardio, dtype: int64

In [87]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25 , random_state=0)

In [88]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((51975, 12), (17326, 12), (51975,), (17326,))

# Logistic Regresion

In [89]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()
logistic.fit(X_train,y_train)

C:\Users\degananda.reddy\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [90]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
accuracy=accuracy_score(y_train,logistic.predict(X_train))

In [91]:
confusion_matrix(y_test,logistic.predict(X_test))

array([[6587, 2066],
       [2796, 5877]], dtype=int64)

In [92]:
accuracy


0.7173256373256374

# KNN Classifier

In [93]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors = 8)
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

In [94]:
knn_pred=knn_classifier.predict(X_test)

In [95]:
knn_accuracy=accuracy_score(y_test,knn_pred)

In [96]:
knn_accuracy

0.6531801916195313

# Random Forest Classifier

In [97]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=10, criterion = 'entropy', random_state = 50)
rf_classifier.fit(X_train,y_train)
pred=rf_classifier.predict(X_test)
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(pred,y_test))
print(confusion_matrix(pred,y_test))
classification_report(pred,y_test)



0.6944476509292393
[[6395 3036]
 [2258 5637]]


'              precision    recall  f1-score   support\n\n           0       0.74      0.68      0.71      9431\n           1       0.65      0.71      0.68      7895\n\n    accuracy                           0.69     17326\n   macro avg       0.69      0.70      0.69     17326\nweighted avg       0.70      0.69      0.70     17326\n'

# XGBOOST Classifier

In [98]:
import xgboost
xgboost.__version__

'0.90'

In [99]:
classifier=xgboost.XGBClassifier()
classifier.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [100]:
xgpred=classifier.predict(X_test)

In [101]:
accuracy_score(y_test,xgpred)

0.734445342260187

In [170]:
X_train.dtypes

age         float64
height      float64
weight      float64
ap_hi       float64
ap_lo       float64
Male_2        uint8
Normal_2      uint8
Normal_3      uint8
gluc_2        uint8
gluc_3        uint8
smoke_1       uint8
alco_1        uint8
dtype: object

In [102]:
import pickle 
filename = 'finalized_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [172]:
pred_data=X_test.iloc[0:1]
pred_data.values
#pred_data.shape,X_train.shape

array([[-0.86565669,  1.17458338,  0.9592312 ,  0.13678216, -0.03516802,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]])

In [176]:
data=[-0.86565669,  1.17458338,  0.9592312 ,  0.13678216, -0.03516802,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]
data_df=pd.DataFrame(columns=X_train.columns)
data_df.loc[0]=data

In [177]:
data_df

age    height    weight     ap_hi     ap_lo  Male_2  Normal_2  \
0 -0.865657  1.174583  0.959231  0.136782 -0.035168     1.0       0.0   

   Normal_3  gluc_2  gluc_3  smoke_1  alco_1  
0       0.0     0.0     0.0      0.0     0.0

In [178]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(data_df)
print(result.flatten())

[1]


In [126]:
type(X_test)

pandas.core.frame.DataFrame

In [111]:
y_test.head

68978    1
54143    0
3004     1
23526    1
54968    1
Name: cardio, dtype: int64

In [179]:
params={
 "learning_rate"    : [0.05, 0.10, 0.15, 0.20, 0.25, 0.30 ] ,
 "max_depth"        : [ 3, 4, 5, 6, 8, 10, 12, 15],
 "min_child_weight" : [ 1, 3, 5, 7 ],
 "gamma"            : [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
 "colsample_bytree" : [ 0.3, 0.4, 0.5 , 0.7 ]
    
}

# Hyper Tuning the model just to check up

In [180]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
classifier=xgboost.XGBClassifier()
random_search=RandomizedSearchCV(classifier,param_distributions=params,n_iter=5,scoring='roc_auc',n_jobs=-1,cv=5,verbose=3)
random_search.fit(X,y)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 out of  25 | elapsed:  2.2min finished


RandomizedSearchCV(cv=5, error_score='raise-deprecating',
                   estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                           colsample_bylevel=1,
                                           colsample_bynode=1,
                                           colsample_bytree=1, gamma=0,
                                           learning_rate=0.1, max_delta_step=0,
                                           max_depth=3, min_child_weight=1,
                                           missing=None, n_estimators=100,
                                           n_jobs=1, nthread=None,
                                           objective='binary:logistic',
                                           random_state=0, reg_alpha=0...
                                           seed=None, silent=None, subsample=1,
                                           verbosity=1),
                   iid='warn', n_iter=5, n_jobs=-1,
                   param_distribu

In [181]:

random_search.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.4, gamma=0.2,
              learning_rate=0.15, max_delta_step=0, max_depth=3,
              min_child_weight=5, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [182]:
random_search.best_params_

{'min_child_weight': 5,
 'max_depth': 3,
 'learning_rate': 0.15,
 'gamma': 0.2,
 'colsample_bytree': 0.4}

In [183]:
classifier=xgboost.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.3, gamma=0.0,
              learning_rate=0.2, max_delta_step=0, max_depth=3,
              min_child_weight=3, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [184]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(classifier,X,y,cv=10)

In [185]:
score

array([0.73322753, 0.72962055, 0.74256854, 0.73650794, 0.73290043,
       0.73852814, 0.72987013, 0.73751804, 0.73261183, 0.73055275])